apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-resource-group
  title: Azure Resource Group Provisioning
  description: A template to create an Azure Resource Group
  tags:
    - azure
    - resource-group
spec:
  type: service
  owner: team@example.com
  parameters:
    - title: Azure Subscription ID
      name: subscriptionId
      description: Enter your Azure Subscription ID
      required: true
      type: string
    - title: Azure Client ID
      name: clientId
      description: Enter your Azure Client ID
      required: true
      type: string
    - title: Azure Client Secret
      name: clientSecret
      description: Enter your Azure Client Secret
      required: true
      type: string
    - title: Azure Tenant ID
      name: tenantId
      description: Enter your Azure Tenant ID
      required: true
      type: string
    - title: Resource Group Name
      name: resourceGroupName
      description: Name of the Azure Resource Group to create
      required: true
      type: string
    - title: Resource Group Location
      name: resourceGroupLocation
      description: Choose the location for the Resource Group
      required: true
      type: string
      enum:
        - eastus
        - westus
        - centralus
        - northeurope
        - westeurope

  steps:
    - id: create-resource-group
      name: Create Azure Resource Group
      action: azure:resourceGroup.create
      input:
        subscriptionId: ${{ parameters.subscriptionId }}
        clientId: ${{ parameters.clientId }}
        clientSecret: ${{ parameters.clientSecret }}
        tenantId: ${{ parameters.tenantId }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.resourceGroupLocation }}

