apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: azure-resource-group-location
  description: Template for creating Azure Resource Groups
spec:
  type: url
  target: https://raw.githubusercontent.com/akashnadimpally/backstageV/main/examples/template/azure-resource-group-template.yaml
